config/routes.rb
Rails.application.routes.draw do
  get 'pages/about_me'
  resources :posts
  devise_for :users, only: :sessions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  # Defines the root path route ("/")
  # root "articles#index"
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :featured_image
    has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:about_me]
  def about_me
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:index, :show, :about_me]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="<%= asset_path('cat.jpg') %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
    <%= yield(:title) %>

    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
 
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class='row'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about_me.html.erb
<% provide(:title, "About Me") %>

<script src="https://kit.fontawesome.com/1d87a2c62d.js" crossorigin="anonymous"></script>
<div class="card-group w-75" style="margin:10%;">
  <div class="card shadow p-3 mb-5 bg-body rounded" style=" border:none">
    <img src="<%= asset_path('bremda.jpg') %>" class="card-img-top rounded-circle w-25 mx-auto" width=10% alt="...">
    <div class="card-body">
      <h1 class="card-title text-center">About me</h1>
      <p class="card-text text-center p-2">
        Eai, beleza?
        Meu nome é Brenda, tenho 20 anos, gosto de gatos(acho que já deu pra entender), sou formada em Técnico em Informática e
        sou estagiária em Análise e Desenvolvimento de Sistemas. Enfim, curto desenvolver algumas coisas aí.
      </p>
      <br>
      <a class="fab fa-linkedin-in p-3" target="_blank" href="https://linkedin.com/in/brenda-valadares" style="color:black;"></a>
      <a class="fab fa-github p-3" target="_blank" href="https://github.com/Bremda" style="color:black;"></a>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='col-6'>
    <br>
    <div class="mb-3">
      <%= form.label 'Title', class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label 'Description', class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="mb-3">
    <%= form.label 'Content', class: 'form-label' %>
    <%= form.rich_text_area :content, class: 'form-control', rows: '15' %>
  </div>
  <div class="mb-3">
    <%= form.submit 'Create', class: 'btn btn-dark btn-sm' %>
    <%= link_to 'Back', root_path, class: 'btn btn-dark btn-sm' %>
  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="h3 text-capitalize">
    <%= post.title %>
  </div>
  <p class="text-muted d-inline-block" style="max-width: 245px; padding:10%; padding-left: 0%">
  <%= post.description %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Home") %>

<p style="color: green"><%= notice %></p>
<div class="header">
  <h1>Posts</h1>
</div>
<div class="mt-1 d-flex justify-content-end">
  <% if user_signed_in? %>
    <%= link_to "New post", new_post_path, class: "btn btn-dark" %>
  <% end %>
</div>
<div id="posts">
  <% @posts.each do |post| %>
    <div class="card" style="width: 18rem; margin:1%; border:none">
      <div class="card-body shadow p-3 mb-5 bg-body rounded" >
        <h5 class="card-title">
          <%= render post %>
        </h5>
        <p>
          <%= link_to "Show this post", post, class:"btn btn-dark" %>
          <% if user_signed_in? %>
            <%= link_to "Delete", post, "data-turbo-method" => :delete, class:"btn btn-dark"%>
            <%= link_to "Edit", edit_post_path(post), class:"btn btn-dark"%>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="title is-1">New Post</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<br>
<br>
<div class="row row-cols-1 row-cols-md-1 g-4">
  <div class="col">
    <div class="card h-800 w-500 shadow p-3 mb-5 bg-body rounded">
      <div class="card-body">
        <h1 class="card-title text-capitalize"><%= @post.title %></h1>
        <p class="card-text" style="padding:1%"><%= @post.content %></p>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar" style="background-color: #E8E7EF;" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <img class="rounded-circle" alt="cat icon" src="<%= asset_path('cat.jpg') %> " width="30">
      <%= link_to 'Home', root_path, class: 'btn' %>
    </div>
    <div class="justify-content-end">
      <% if user_signed_in? %>
        <a href="/posts/new" class="btn" tabindex="-1" role="button" aria-disabled="true">New Post</a>
      <% end %>
      <%= link_to "About Me", pages_about_me_path, class:"btn" %>
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, "data-turbo-method" => :delete, class: "btn" %>
      <% else %>
        <a class="btn btn-dark" href='/users/sign_in' tabindex="-1" role="button" aria-disabled="true">
          Sign In
        </a>
      <% end %>
    </div>
  </div>
</nav>